name: motionformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - av=8.0.3=py38hcaf3a0b_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - ffmpeg=4.3.1=h167e202_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.1=h27cfd23_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py38h27cfd23_1
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.1=py38ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.2=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.2=py38h2d18471_0
  - numpy-base=1.20.2=py38hfae3a4d_0
  - olefile=0.46=py_0
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1k=h7f98852_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=21.1.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python_abi=3.8=1_cp38
  - pytorch=1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.9.1=py38_cu102
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - chardet==4.0.0
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - ffmpeg-python==0.2.0
    - future==0.18.2
    - fvcore==0.1.5
    - idna==2.10
    - iopath==0.1.8
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - pandas==1.2.4
    - psutil==5.8.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - timm==0.4.9
    - tqdm==4.61.0
    - urllib3==1.26.5
    - werkzeug==2.0.1
prefix: /private/home/mandelapatrick/.conda/envs/motionformer
